language: rust
rust: nightly

matrix:
  include:
    - env: TARGET_BUILD=thumbv6m-none-eabi
      rust: nightly
    - env: TARGET_BUILD=thumbv7em-none-eabihf
      rust: nightly
    - env: TARGET_BUILD=armv7-unknown-linux-gnueabihf
      rust: nightly
    - env: TARGET_BUILD=x86_64-unknown-linux-gnu
      rust: nightly

install:
  - rustup component add rustfmt-preview
  - rustup target add $TARGET_BUILD || true

script:
  - cargo fmt --all -- --check
  - cargo check --target $TARGET_BUILD

after_script: set +e

cache:
  cargo: true

before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never